snakefile: Snakefile

# executable: "singularity run ../frictionlesser.sif"
executable: "../../release/app/frictionlesser"

expe-name: 20230210_PARIS

sizes:
    - 10
    - 20
    - 30

# Number of runs = number of (possibly duplicated) signatures.
runs: 5000

