snakefile: Snakefile

# executable: "singularity run ../../frictionlesser.sif"
executable: "../../release/app/frictionlesser"

cluster: "sbatch --job-name {resources.job_name} --mem 16G --cpus-per-task=1 --partition common,dedicated --qos fast --output logs/%j.out --error logs/%j.err"

sizes:
    - 10
    - 20
    - 30

