snakefile: Snakefile

# executable: "singularity run ../frictionlesser.sif"
executable: "../../release/app/frictionlesser"

cluster: "sbatch --job-name {resources.job_name} --mem {resources.mem_mb} --cpus-per-task=1 --partition common,dedicated --qos normal --output slurmout/%j.out --error slurmout/%j.err"

sizes:
    - 10
    - 20
    - 30

# Number of runs = number of (possibly duplicated) signatures.
runs: 5000

